# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221205_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfiguration',
            name='startingDate',
            field=models.DateTimeField(default=None),
        ),
    ]
