# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-05 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfioguration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('endpointForFetching', models.CharField(max_length=1000)),
                ('endpointForPosting', models.CharField(max_length=1000)),
            ],
        ),
    ]
