# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-05 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_modelconfioguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfioguration',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
