# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-05 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221205_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelConfioguration',
            new_name='ModelConfiguration',
        ),
    ]
